replicaCount: 1
name: persephone
namespace: homolog

containers:
  - name: persephone
    image: nexus.sigame.com.br/persephone:2.1.0
    env:
    - name: NODE_ENV
      value: "sit"
    - name: MONGO_URI
      value: "mongodb://lnxbrspmongodb01.subpriv.vcnuat.oraclevcn.com:41000"
    - name: MONGO_DB_NAME
      value: "persephone"
    - name: MONGO_USER
      value: "persephone"
    - name: MONGO_PASSWORD
      value: "LINDASFgwqFDT434adads"
    - name: KAFKA_CLIENT_ID
      value: "persephone.lionx.com.br"
    - name: KAKFA_BROKERS
      value: "cluster-kafka-bootstrap.kafka.svc.cluster.local:9092"
    - name: PERSEPHONE_LOG_LEVEL
      value: "info"
    - name: KAFKA_LOG_LEVEL
      value: "0"

imagePullSecrets:
  - name: nexus-v3
  
labels:
  app: persephone

podAnnotations: {}

# securityContext:
#   capabilities:
#     drop:
#     - AUDIT_WRITE
#     - MKNOD
#     - SETFCAP
#     - SETPCAP
#     - KILL
#   # runAsNonRoot: true
#   # runAsUser: 1000
resources:
  requests: #Amount of resources kube-scheduler will look into nodes to alocate the given POD
    cpu: 512m
    memory: 256Mi
  limits: #Amount of resources limited by kubelet (will not exceed)
    cpu: 1
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}